$lock_cmd = pidof hyprlock || hyprlock
$suspend_cmd = pidof steam || systemctl suspend || loginctl suspend # fuck nvidia

general {
    lock_cmd = $lock_cmd
    before_sleep_cmd = loginctl lock-session
}

listener {
    timeout = 600
    on-timeout = gammastep -l 0:0 -o -b 0.8:0.8 -O 6500K
    on-resume = pkill gammastep
  }

listener {
    timeout = 900                                 # 15min
    on-timeout = loginctl lock-session            # lock screen when timeout has passed
}

listener {
    timeout = 930
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}
