hl.permission({binary = "/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", type="screencopy", mode="allow"})
hl.permission({binary = "/usr/bin/obs", type="screencopy", mode="allow"})
hl.permission({binary = "/usr/bin/hyprpicker", type="screencopy", mode="allow"})
hl.permission({binary = "/opt/(discord-canary|discord)/(DiscordCanary|Discord)", type="screencopy", mode="allow"})
hl.permission({binary = "/usr/bin/vesktop", type="screencopy", mode="allow"})
hl.permission({binary = "/usr/bin/grim", type="screencopy", mode="allow"})
hl.permission({binary = "/usr/(bin|local/bin)/hyprpm", type="plugin", mode="allow"})
